[project]
protostar-version = "0.9.0"
lib-path = "lib"

[contracts]
BuyMeACoffee = ["contracts/BuyMeACoffee.cairo"]

[format]
target = ["src", "tests"]
ignore-broken = true

[profile.devnet.project]
gateway-url = "http://127.0.0.1:5050/"
chain-id = 1536727068981429685321

[profile.testnet.project]
network="testnet"

[profile.testnet2.project]
gateway-url = "https://alpha4-2.starknet.io"
chain-id = 393402129659245999442226

["profile.devnet.protostar.deploy"]
gateway-url="http://127.0.0.1:5050/"

["profile.testnet.protostar.deploy"]
network="testnet"

["profile.testnet2.protostar.deploy"]
gateway-url = "https://alpha4-2.starknet.io"

["profile.mainnet.protostar.deploy"]
network="mainnet"